services:
  - type: web
    name: matrix-bot-hub
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: ADMIN_PASSWORD
        value: "vern19"
      - key: FLASK_SECRET_KEY
        generateValue: true
